dist: focal
language: python

python:
  - '3.8'

install: sudo ./.ci/install_dependencies.sh /bioinf-tools

before_script:
    - export PATH=/bioinf-tools:$PATH

script:
  - tox

notifications:
  email: false

